# This rule is not used by the project operator-demo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.crd.pachirode.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: application-admin-role
rules:
- apiGroups:
  - core.crd.pachirode.com
  resources:
  - applications
  verbs:
  - '*'
- apiGroups:
  - core.crd.pachirode.com
  resources:
  - applications/status
  verbs:
  - get
